version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crypto"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wnkj56e1uavz"
s3_prefix = "crypto"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
